<?php

return [
    '#100' => ['message' => 'Continue', 'status_code' => 100],
    '#101' => ['message' => 'Switching Protocols', 'status_code' => 100],
    '#102' => ['message' => 'Processing', 'status_code' => 100],
    '#103' => ['message' => 'Early Hints', 'status_code' => 100],
    '#200' => ['message' => 'OK', 'status_code' => 200],
    '#201' => ['message' => 'Created', 'status_code' => 201],
    '#202' => ['message' => 'Accepted', 'status_code' => 202],
    '#203' => ['message' => 'Non-Authoritative Information', 'status_code' => 203],
    '#204' => ['message' => 'No Content', 'status_code' => 203],
    '#205' => ['message' => 'Reset Content', 'status_code' => 205],
    '#206' => ['message' => 'Partial Content', 'status_code' => 206],
    '#207' => ['message' => 'Multi-status_code', 'status_code' => 207],
    '#208' => ['message' => 'Already Reported', 'status_code' => 208],
    '#226' => ['message' => 'IM Used', 'status_code' => 226],
    '#300' => ['message' => 'Multiple Choices', 'status_code' => 300],
    '#301' => ['message' => 'Moved Permanently', 'status_code' => 301],
    '#302' => ['message' => 'Found', 'status_code' => 302],
    '#303' => ['message' => 'See Other', 'status_code' => 303],
    '#304' => ['message' => 'Not Modified', 'status_code' => 304],
    '#305' => ['message' => 'Use Proxy', 'status_code' => 305],
    '#307' => ['message' => 'Temporary Redirect', 'status_code' => 307],
    '#308' => ['message' => 'Permanent Redirect', 'status_code' => 308],
    '#400' => ['message' => 'Bad Request', 'status_code' => 400],
    '#401' => ['message' => 'Unauthorized', 'status_code' => 401],
    '#402' => ['message' => 'Payment Required', 'status_code' => 402],
    '#403' => ['message' => 'Forbidden', 'status_code' => 403],
    '#404' => ['message' => 'Not Found', 'status_code' => 404],
    '#405' => ['message' => 'Method Not Allowed', 'status_code' => 405],
    '#406' => ['message' => 'Not Acceptable', 'status_code' => 406],
    '#407' => ['message' => 'Proxy Authentication Required', 'status_code' => 407],
    '#408' => ['message' => 'Request Timeout', 'status_code' => 408],
    '#409' => ['message' => 'Conflict', 'status_code' => 409],
    '#410' => ['message' => 'Gone', 'status_code' => 410],
    '#411' => ['message' => 'Length Required', 'status_code' => 411],
    '#412' => ['message' => 'Precondition Failed', 'status_code' => 412],
    '#413' => ['message' => 'Payload Too Large', 'status_code' => 413],
    '#414' => ['message' => 'URI Too Long', 'status_code' => 414],
    '#415' => ['message' => 'Unsupported Media Type', 'status_code' => 415],
    '#416' => ['message' => 'Range Not Satisfiable', 'status_code' => 416],
    '#417' => ['message' => 'Expectation Failed', 'status_code' => 417],
    '#418' => ['message' => 'I\'m a teapot', 'status_code' => 418],
    '#421' => ['message' => 'Misdirected Request', 'status_code' => 421],
    '#422' => ['message' => 'Unprocessable Entity', 'status_code' => 422],
    '#423' => ['message' => 'Locked', 'status_code' => 423],
    '#424' => ['message' => 'Failed Dependency', 'status_code' => 424],
    '#425' => ['message' => 'Reserved for WebDAV advanced collections expired proposal', 'status_code' => 425],
    '#426' => ['message' => 'Upgrade Required', 'status_code' => 426],
    '#428' => ['message' => 'Precondition Required', 'status_code' => 428],
    '#429' => ['message' => 'Too Many Requests', 'status_code' => 429],
    '#431' => ['message' => 'Request Header Fields Too Large', 'status_code' => 431],
    '#451' => ['message' => 'Unavailable For Legal Reasons', 'status_code' => 451],
    '#499' => ['message' => 'Client has closed connection', 'status_code' => 499],
    '#500' => ['message' => 'Internal Server Error', 'status_code' => 500],
    '#501' => ['message' => 'Not Implemented', 'status_code' => 501],
    '#502' => ['message' => 'Bad Gateway', 'status_code' => 502],
    '#503' => ['message' => '系统维护中：Service Unavailable', 'status_code' => 503],
    '#504' => ['message' => 'Gateway Timeout', 'status_code' => 504],
    '#505' => ['message' => 'HTTP Version Not Supported', 'status_code' => 505],
    '#506' => ['message' => 'Variant Also Negotiates', 'status_code' => 506],
    '#507' => ['message' => 'Insufficient Storage', 'status_code' => 507],
    '#508' => ['message' => 'Loop Detected', 'status_code' => 508],
    '#510' => ['message' => 'Not Extended', 'status_code' => 510],
    '#511' => ['message' => 'Network Authentication Required', 'status_code' => 511],
    '#1' => ['message' => '网络错误', 'status_code' => 400],

    '#2' => ['message' => '未授权', 'status_code' => 400],
    '#3' => ['message' => '今天你已经领取过积分了', 'status_code' => 400],
    '#4' => ['message' => '积分不足', 'status_code' => 400],
    '#5' => ['message' => '谢谢参与', 'status_code' => 400],
    '#6' => ['message' => '请完善收货地址', 'status_code' => 400],

    '#1001' => ['message' => '手机号格式不正确', 'status_code' => 400],
    '#1002' => ['message' => '手机号不存在或密码错误', 'status_code' => 400],
    '#1003' => ['message' => '账号禁止登陆', 'status_code' => 400],
    '#1004' => ['message' => '不能重复发送验证码', 'status_code' => 400],
    '#1005' => ['message' => '验证码已失效', 'status_code' => 400],
    '#1006' => ['message' => '验证码错误', 'status_code' => 400],




    '#60001' => ['message' => '订单不存在', 'status_code' => 404],
    '#60002' => ['message' => '交易密码未设置不可交易', 'status_code' => 403],
    '#60003' => ['message' => '交易密码不能为空', 'status_code' => 403],
    '#60004' => ['message' => '交易密码错误', 'status_code' => 403],
    '#60005' => ['message' => '交易对不存在', 'status_code' => 404],
    '#60006' => ['message' => '交易未开启', 'status_code' => 403],
    '#60007' => ['message' => '余额不足', 'status_code' => 403],
    '#60008' => ['message' => '市价单不可撤销', 'status_code' => 403],
    '#60009' => ['message' => '购买数量超出限制', 'status_code' => 403],
    '#60010' => ['message' => '自己不能购买自己的单', 'status_code' => 403],
    '#60011' => ['message' => '交易对必传', 'status_code' => 422],
    '#60012' => ['message' => '交易对错误', 'status_code' => 400],

    '#60013' => ['message' => '没有足够的币', 'status_code' => 400],
    '#60014' => ['message' => '不能购买自己的订单', 'status_code' => 400],
    '#60015' => ['message' => '不能低于最小购买数量', 'status_code' => 400],
    '#60016' => ['message' => '不能高于最大购买数量', 'status_code' => 400],
    '#60018' => ['message' => '您有未付款订单，不能再次进行购买', 'status_code' => 400],
];
